spring:
  datasource:
    url: jdbc:sqlite:${user.home}/material-lib/materials.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      connection-init-sql: PRAGMA foreign_keys=ON

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8080
